name: flutter_piano
description: A Flutter Piano Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
